name: test
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies, truffle, and ganache-cli
        run: |
          npm install -g truffle
          npm install -g ganache-cli
          npm install
      - name: start ganache
        run: ganache-cli
      - name: Test
        run: |
          npm run test
